sudo: false
language: node_js
node_js:
- 'node'
script:
- npm run test
- npm run prod
cache:
  directories:
    - node_modules
deploy:
  - provider: npm
    email: waltshirey@gmail.com
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET_NAME
    upload_dir: dxp-questions-ui/lib/$TRAVIS_TAG
    local_dir: dist
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api-key: $GITHUB_AUTH_TOKEN
    file: /dist/dxp-questions-min.js
    skip_cleanup: true
    on:
      tags: true
notifications:
  hipchat: $HIPCHAT_AUTH_TOKEN@$HIPCHAT_ROOM_ID